name: Send updates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.2.2
        with:
          workflow: Update submodules
          repo: dhinakg/ellekit-official
          token: ${{ secrets.ACCESS_TOKEN }}
